baseURL = "https://endocrino.katia.vet/"
title = "Endocrinologia veterinária - Katia Mogioni de Abreu"
languageCode = "pt-BR"
DefaultContentLanguage = "pt"
paginate = 3

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[module]
  [[module.mounts]]
    source = "./assets"
    target = "assets"

  [[module.mounts]]
    source = "./static"
    target = "static"

  [[module.mounts]]
    source = "./node_modules/bootstrap/scss/"
    target = "assets/scss/bootstrap"

  [[module.mounts]]
    source = "./node_modules/bootstrap-icons/font/"
    target = "assets/css/bootstrap-icons"

  [[module.mounts]]
    source = "./node_modules/bootstrap-icons/font/"
    target = "assets/css/bootstrap-icons"

  [[module.mounts]]
    source = "./node_modules/bootstrap-icons/font/fonts"
    target = "static/css/bootstrap-icons/fonts"

  [[module.mounts]]
    source = "./node_modules/@fortawesome/fontawesome-free/css"
    target = "assets/css/fontawesome"

  [[module.mounts]]
    source = "./node_modules/@fortawesome/fontawesome-free/webfonts"
    target = "static/css/webfonts"

  [[module.mounts]]
    source = "./node_modules/jquery/dist"
    target = "assets/js/jquery"

  [[module.mounts]]
    source = "./node_modules/bootstrap/dist/js"
    target = "assets/js/bootstrap"

  [[module.mounts]]
    source = "./node_modules/imagesloaded"
    target = "assets/js/imagesloaded"

  [[module.mounts]]
    source = "./node_modules/slick-carousel/slick"
    target = "assets/js/slick"

  [[module.mounts]]
    source = "./node_modules/slick-carousel/slick"
    target = "assets/css/slick"

  [[module.mounts]]
    source = "./node_modules/waypoints/lib"
    target = "assets/js/waypoints"

  [[module.mounts]]
    source = "./node_modules/greensock/dist"
    target = "assets/js/tweenmax"

  [[module.mounts]]
    source = "./node_modules/masonry-layout/dist"
    target = "assets/js/masonry-layout"

  [[module.mounts]]
    source = "./node_modules/magnific-popup/dist"
    target = "assets/js/magnific-popup"

  [[module.mounts]]
    source = "./node_modules/magnific-popup/dist"
    target = "assets/css/magnific-popup"

# Main Menu
[[menu.main]]
name = "Início"
url = "#inicio"
weight = 1
[[menu.main]]
name = "Sobre mim"
url = "#sobre-mim"
weight = 2
[[menu.main]]
name = "Carreira"
url = "#carreira"
weight = 3
[[menu.main]]
name = "O que é a Endocrinologia"
url = "#endocrinologia"
weight = 4

# Sitemap Menu
[[menu.sitemap]]
name = "Início"
url = "#inicio"
weight = 1
[[menu.sitemap]]
name = "Sobre mim"
url = "#sobre-mim"
weight = 2
[[menu.sitemap]]
name = "Carreira"
url = "#carreira"
weight = 3
[[menu.sitemap]]
name = "O que é a Endocrinologia"
url = "#endocrinologia"
weight = 4
[[menu.sitemap]]
name = "Contato"
url = "contato"
weight = 5

[params]
seoDescription = "A Endocrinologia veterinária atende cães e gatos com problemas em glândulas secretoras de hormônios ou condições relacionadas ao metabolismo, como as modificações químicas que as substâncias sofrem no organismo dos pets."
contactLink = "contato"
copyright = "Todos direitos reservados © Katia Mogioni de Abreu 2021"
footerLogo = "images/logo-alternative.png"
formspreeURL = "https://formspree.io/f/mnqldvda"
googleAnalytics = "G-6HMVW4Z9B0"
logo = "images/logo.png"
ogImage = "images/dog-field-banner.jpg"

[params.address]
title = "Contato"
address = "São Paulo e Guarulhos"
email = "endocrino@katia.vet"
phone = "+(55) 11 97289 9833"
phoneRaw = "5511972899833"

# Social icons
[[params.social]]
icon = "bi-facebook"
name = "endocrinokatiavet"
url = "https://www.facebook.com/endocrinokatiavet/"
weight = 1
[[params.social]]
icon = "bi-instagram"
name = "@endocrino_katia"
url = "https://www.instagram.com/endocrino_katia"
weight = 2

[params.help]
id = "contato"
title = "Dúvidas?"
button = "Entre em contato"
